### ISSUE TITLE
Wrong annotations for detection and segmentation

### ISSUE THREAD

**Issue by joeyy5588** [askforalfred/alfred#114]
Hi,

I followed the instruction from here (https://github.com/alfworld/alfworld/tree/master/alfworld/data) to generate training images for my own detector, and when I visualized some of the images, I found all of the **Faucet** in the bathroom are mislabeled as **FloorLamp** (please see the below images). I'm pretty sure I map the class name correctly, since the rest of the classes are correctly visualized.

p.s. I check the meta file for these images and none of these files include the word "Faucet".

Can you help me fix this issue? Thanks!
![image](https://user-images.githubusercontent.com/24842980/165027849-5a0dd6d5-9c15-4513-9223-ad5869c96bcf.png)
![image](https://user-images.githubusercontent.com/24842980/165027933-eeec4f9a-5f4c-40db-8a48-c047ce3f9355.png)

**Comment by MohitShridhar** [comment]
@joeyy5588, thanks for reporting this.

This looks like a bug in Ai2THOR 2.1.0 that was probably fixed in later releases. There is no easy way to fix this without recompiling the Unity build and creating a new 2.1.0 binary.

But for now, a quick hack might be to force all `FloorLamp` objects to `Faucet` since there should be no FloorLamps in Bathrooms as per the [documentation](https://ai2thor.allenai.org/ithor/documentation/objects/object-types/#FloorLamp).

Hope this helps!
