### ISSUE TITLE
Extracting Resnet Features for the Full Dataset

### ISSUE THREAD

**Issue by agneet42** [askforalfred/alfred#126]
I am trying to extract resnet features using the command `python models/utils/extract_resnet.py --data data/full_2.1.0 --batch 32 --gpu --visual_model resnet18 --filename feat_conv.pt` ,  for the full dataset I was hoping to understand how long (~estimate) this takes (on a GPU) and what are the total number of `feat_conv.pt` that I can expect at the end of succesfull execution?

**Comment by MohitShridhar** [comment]
@agneet42, sorry, I don't remember because it's been 3 years since I ran this script. But maybe time one/few batch(es), and then try to extrapolate how long the full dataset would take? 

The total number of `feat_conv.pt` should be the size of [this os.walk](https://github.com/askforalfred/alfred/blob/master/models/utils/extract_resnet.py#L34)

**Comment by agneet42** [comment]
Thanks @MohitShridhar , looks like I was able to generate all the features. Took close to 1 day and generated about 7080 samples!
