### ISSUE TITLE
Stuck in controller.step()

### ISSUE THREAD

**Issue by wzcai99** [askforalfred/alfred#130]
I follow the installation instructions and trying to run check_thor.py, but I was stuck when calling c.step(),
```
python ./scripts/check_thor.py
thor-201909061227-Linux64: [|||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%   1.7 MiB/s]  of 390.MB
Found path: /home/henry/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/henry/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/henry/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1024x768 (primary device).
Logging to /home/henry/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
```

When I look into the log file, I got one error:
```
CAMERA DEPTH TEXTURE SET TO: Depth

(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

SocketException: The socket has been shut down
  at System.Net.Sockets.Socket.Send (System.Byte[] buf) [0x00000] in <filename unknown>:0
  at AgentManager+<EmitFrame>c__Iterator3.MoveNext () [0x00000] in <filename unknown>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <>

(Filename:  Line: -1)
```

Could you give me some suggestions on this problem? Thank you.

**Comment by MohitShridhar** [comment]
@wzcai99, I am not sure what is happening here. Maybe try reinstalling like here: https://github.com/allenai/ai2thor/issues/1105

Also try asking on ai2thor/issues: https://github.com/allenai/ai2thor/issues

**Comment by wzcai99** [comment]
@MohitShridhar I found using another version of ai2thor fix this problem, but is the alfred code, e.g the class ThorEnv compatible with another version of ai2thor?

**Comment by gautierdag** [comment]
@wzcai99 what version of ai2thor fixed this for you? 

I've haven't been able to fix the `SocketException`.

**Comment by wzcai99** [comment]
@gautierdag I still use the ai2thor version 2.1.0, and I fixed the error by replacing the version of two packages werkzeug and flask. Try this
`pip instal werkzeug==2.03 flask==2.0.3`

**Comment by gautierdag** [comment]
You can't understand how long I've spent trying to fix this. I was persuaded it was an error with my Xorg setup. Thank you!

**Comment by Wang1665941855** [comment]
> You can't understand how long I've spent trying to fix this. I was persuaded it was an error with my Xorg setup. Thank you!
Can you tell me your Xorg setup? thanks you

**Comment by Wang1665941855** [comment]
@gautierdag  Can you tell me your Xorg setup? Thank you.

**Comment by Wang1665941855** [comment]
@gautierdag Thank you for your reply. I use my laptop to connect to the server to run the code. When I execute startx.py and then run check_thor.py, and then a dialog box in aithor2 will pop up, displaying a picture, but the program will continue to execute unless you manually stop the code. That is, I can't  normally run check_thor.py, is this the problem with Xorg setup? Can you help me? Thank you very much.
My server system is Linux Ubuntu.

**Comment by jiadingfang** [comment]
Same error running `check_thor.py`, and the above solution updating werkzeug and flask does not help as I'm running locally so there is no socket problem. However, this is what I got
>(alfred) fjd:~/alfred$ python scripts/check_thor.py
Found path: /home/fjd/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/fjd/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/fjd/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 'DELL U2422H 24"': 1920x1080 (primary device).
Logging to /home/fjd/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
^CTraceback (most recent call last):
  File "scripts/check_thor.py", line 5, in <module>
    event = c.step(dict(action="MoveAhead"))
  File "/home/fjd/miniconda3/envs/alfred/lib/python3.8/site-packages/ai2thor/controller.py", line 654, in step
    self.last_event = queue_get(self.request_queue)
  File "/home/fjd/miniconda3/envs/alfred/lib/python3.8/site-packages/ai2thor/server.py", line 41, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/home/fjd/miniconda3/envs/alfred/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/fjd/miniconda3/envs/alfred/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

As of today, the pytorch version 1.1.0 is not available, so when installing ALFRED, I remove all version numbers in `requirements.txt` except `ai2thor==2.1.0` because it is said to be critical for ALFRED.

**Comment by Taichi-Pink** [comment]
> @gautierdag I still use the ai2thor version 2.1.0, and I fixed the error by replacing the version of two packages werkzeug and flask. Try this `pip instal werkzeug==2.03 flask==2.0.3`

Thanks! This helped me out of the problem. But the command has a typo and should be`pip instal werkzeug==2.0.3 flask==2.0.3` :)
