### ISSUE TITLE
Human-in-the-loop with planner?

### ISSUE THREAD

**Issue by siddk** [askforalfred/alfred#4]
Is there a straightforward way to couple the existing PDDL code with the ability to interactively control the agent in an environment?

For example in a collaborative setting: I want to load an initial state, let the human explore/perform part of the task, then use the planner to finish/satisfy the high-level goal in case the human fails.

**Comment by MohitShridhar** [comment]
Well it's definitely possible, but requires some effort with the current setup. From our experience, the PDDL planner is a bit flaky and fails occasionally. But with human demonstrations, you might also reach states where no valid plans exist, for e.g: if the task is to put an apple in the fridge, but the human slices the only apple in the scene, the planner will fail because you can't 'unslice' an apple to recover from this. 

But it should be possible to replan at any given state (success not guaranteed!). It's a bit complicated, but I'd recommend stepping through [this loop](https://github.com/askforalfred/alfred/blob/bc9c64cb7aefc154c927ceb1173cdcb5faec29a7/gen/scripts/generate_trajectories.py#L555) to understand how planning works for a random scene. The PDDL goals are [here](https://github.com/askforalfred/alfred/blob/master/gen/goal_library.py), along with the [domain description](https://github.com/askforalfred/alfred/blob/master/gen/planner/domains/PutTaskExtended_domain.pddl).

**Comment by siddk** [comment]
Great thanks so much! Out of curiosity - where does the flakiness in the PDDL planner come from? What sort of things does it fail to compensate for?

**Comment by MohitShridhar** [comment]
Well the PDDL planner solves NP-hard problems, so some complex scenarios might exceed the 30s timeout limit. @danielgordon10 might have more insights, but the [solver itself](https://github.com/askforalfred/alfred/tree/master/gen/ff_planner) might have bugs. 

The planner also heavily relies on the [domain description](https://github.com/askforalfred/alfred/blob/master/gen/planner/domains/PutTaskExtended_domain.pddl) for world dynamics. But this isn't perfect. For instance, it knows that a plate can be placed inside a microwave (defined as symbolic predicates), but in reality a specific plate might be too big to fit inside the microwave. These types of failures only happen when you try out the plan in the simulator.

**Comment by MohitShridhar** [comment]
Closing for now.
