### ISSUE TITLE
Why repeating the same frame to predict <<stop>>?

### ISSUE THREAD

**Issue by Ryou0634** [askforalfred/alfred#53]
Hi,

I have a question about this line.
https://github.com/askforalfred/alfred/blob/6d78d8085699da35371c5f65339a470ffcf89a3e/models/model/seq2seq_im_mask.py#L121

If I understand correctly, `frames` contains an image which conditions the prediction of `action_low` of the same index.
I assume that the `im[-1]` in this line is the image when executing the last actual action (e.g. Slice an object), but to predict the stop action, it would be natural to use a new image after the last actual action.
Why does it repeat the same frame, or is my understanding correct? Thanks!

**Comment by MohitShridhar** [comment]
@Ryou0634, during generation, we saved 10 extra frames after the last action (see [this](https://github.com/askforalfred/alfred/blob/3ac425884b96927b043b90cb431fd0568c8c8da3/gen/agents/semantic_map_planner_agent.py#L40)). So technically `im[-1]` should be after the last action.

**Comment by Ryou0634** [comment]
OK, I see that 10 extra frames are saved, but what about the generated ResNet feature in `json_feat_2.1.0`?

Here’s what I’m seeing. I’m reading data from `json_feat_2.1.0`.
`ex['plan']['low_actions']`contains n actions (a_{0}, …,a_{n-1}), and `im` contains n frame features (f_{0}, …, f_{n-1}),
just before [this line](https://github.com/askforalfred/alfred/blob/6d78d8085699da35371c5f65339a470ffcf89a3e/models/model/seq2seq_im_mask.py#L121).

My understanding is that f_{t} is used to predict a_{t}, and we need additional frame to predict <<stop>>, like this.

Executed Action:  <<go>>, a_{0},…, a_{n-2}, a_{n-1}
Frames:                   f_{0},        f_{1}, …, f_{n-1}, f_{n}
Predicted Action: a_{0},       a_{1}, …, a_{n-1}, <<stop>>

So, if im[-1] corresponds to f_{n-1}, it does not make sense to copy f_{n-1} to f_{n} to me...
Any clarification is helpful!

**Comment by MohitShridhar** [comment]
Hmm.. sorry maybe I am misunderstanding something, but in your description, if f_{n} is the last frame, then `im[-1]` _does_ correspond to f_{n} and not f_{n-1}, right? Because in `im[-1]` is [the last element of the list](https://stackoverflow.com/questions/930397/getting-the-last-element-of-a-list)? Or am I missing something?

**Comment by Ryou0634** [comment]
Thank you for your patient response. Let me clarify my understanding.

I see that `ex['plan']['low_actions']` contains only actual actions without `\<stop\>` (e.g., `LookDown, ..., PutObject`).
`len(ex['plan']['low_actions'])` and `len(im.shape[0])` are the same number, so I assume that we need one extra frame to predicting `\<stop\>`.
However, `im[-1]` is actually a frame to predict the last actual action (e.g., `PutObject`), and the frame to predict `\<stop\>` should be a new frame, not `im[-1]`, I think.

**Comment by davidnvq** [comment]
@Ryou0634 What you think is correct. In order to predict `<stop>`, we may use a new frame after we finish all the actions. As Mohit clarified, the last 10 frames are actually similar and the exact new frame you are looking for. Say we have `n` low actions (including the `<stop>` action). In order to predict the low action `i`, we need to use frame `i-1`. And to predict the `stop` action, we need to use frame `n-1`. I believe that the last 10 frames here are actually the frame `n-1`. Since the `<stop>` action make no change to the environment, frame `n-1` or frame `n`, or frame `n+1` are all similar.

**Comment by MohitShridhar** [comment]
@davidnvq thanks! Yes, this is correct with full `feat_conv.pt` files from the Full Dataset.

@Ryou0634 I think you might be right. Thanks for looking into this! I'll look at it in depth soon. A quick fix might be to simply append the last frame feat from the Full Dataset.

**Comment by Ryou0634** [comment]
@MohitShridhar Sure, thanks! Meanwhile I'll generate a feature for the last frame for my purpose : )
@davidnvq Thank you!

**Comment by MohitShridhar** [comment]
Ok, fixed the `feat_conv.pt` files in [Modeling Quickstart](https://ai2-vision-alfred.s3-us-west-2.amazonaws.com/json_feat_2.1.0.7z) and the loader [here](https://github.com/askforalfred/alfred/blob/master/models/model/seq2seq_im_mask.py#L112).
