### ISSUE TITLE
max_fails argument for leaderboard.py

### ISSUE THREAD

**Issue by chanhee-luke** [askforalfred/alfred#83]
Hello,

I saw in the leaderboard.py script that there is a max_fails argument set to 10. Is this argument used to prevent models from exploiting information of action failing? If it is, I wonder why the value 10 was chosen. Thank you in advance for your answer!

**Comment by MohitShridhar** [comment]
@chanhee-luke, yes, `max_fails` is a limit that prevents agents from exhaustively trying out all actions by exploiting the simulator. For example during navigation, agents could bump along walls and corners instead of actually learning to navigate. We chose 10 to keep the limit as low as possible while still allowing for some unforeseen failures like collisions.
